/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Mycal extends javax.swing.JFrame {
	int firstInt;            // ParseInt(firstString) 
	String firstString;      // first input String 
	int nextInt;    	     // ParseInt(nextInt)
	String nextString;       // next Input String 
	int resultInt;           // Mycal result
	String saveHere = "";    // save number
	String tmp = "";         
	
	
	/**
	 * 	숫자 버튼 액션리스너 수정
	 *  사칙연산 메소드 수정 (중복 부분 제거 - 메소드 택1) 
	 * */
	
	/**
	 * Creates new form MyCal
	 */
	public Mycal() {
		super("::���� ���� ���� v1.1::");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		tfMain = new javax.swing.JTextField();
		button2 = new javax.swing.JButton();
		button1 = new javax.swing.JButton();
		button4 = new javax.swing.JButton();
		button5 = new javax.swing.JButton();
		button6 = new javax.swing.JButton();
		button3 = new javax.swing.JButton();
		button8 = new javax.swing.JButton();
		button7 = new javax.swing.JButton();
		button9 = new javax.swing.JButton();
		plus = new javax.swing.JButton();
		minus = new javax.swing.JButton();
		multiplication = new javax.swing.JButton();
		result = new javax.swing.JButton();
		division = new javax.swing.JButton();
		clear = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		button1.setText("1");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});
		
		button2.setText("2");
		button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button2ActionPerformed(evt);
			}
		});
		
		button3.setText("3");
		button3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button3ActionPerformed(evt);
			}
		});

		button4.setText("4");
		button4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button4ActionPerformed(evt);
			}
		});

		button5.setText("5");
		button5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button5ActionPerformed(evt);
			}
		});

		button6.setText("6");
		button6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button6ActionPerformed(evt);
			}
		});
		
		button7.setText("7");
		button7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button7ActionPerformed(evt);
			}
		});

		button8.setText("8");
		button8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button8ActionPerformed(evt);
			}
		});

	

		button9.setText("9");
		button9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button9ActionPerformed(evt);
			}
		});

		plus.setText("+");
		plus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				plusActionPerformed(evt);
			}
		});

		minus.setText("-");
		minus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				minusActionPerformed(evt);
			}
		});

		multiplication.setText("*");
		multiplication.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				multiplicationActionPerformed(evt);
			}
		});

		result.setText("=");
		result.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resultActionPerformed(evt);
			}
		});

		division.setText("/");
		division.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				divisionActionPerformed(evt);
			}
		});

		clear.setText("C");
		clear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(87, 87, 87)
										.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												plus, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(22, 22, 22).addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(tfMain)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE,
																48, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(button5,
																javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE,
																48, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(button8,
																javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(layout.createSequentialGroup()
																.addComponent(clear,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		division,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(button6,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(minus,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(button9,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(multiplication,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(22, 22, 22)
										.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(210, Short.MAX_VALUE))));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { button1, button2, button3,
				button4, button5, button6, button7, button8, button9, division, minus, multiplication, plus });

		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(36, 36, 36)
				.addComponent(
						tfMain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(28, 28, 28)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(multiplication))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(division).addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(17, Short.MAX_VALUE))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(106, 106, 106)
								.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(206, Short.MAX_VALUE))));

		layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { button1, button2, button3,
				button4, button5, button6, button7, button8, button9, division, minus, multiplication, plus });

		pack();
	}// </editor-fold>

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "1");
		tmp = tmp + "1";

	}

	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		tfMain.setText(tmp + "2");
		tmp = tmp + "2";
	}

	private void button3ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "3");
		tmp = tmp + "3";

	}

	private void button4ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "4");
		tmp = tmp + "4";

	}

	private void button5ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "5");
		tmp = tmp + "5";

	}

	private void button6ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "6");
		tmp = tmp + "6";

	}

	private void button7ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "7");
		tmp = tmp + "7";

	}

	private void button8ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "8");
		tmp = tmp + "8";

	}

	private void button9ActionPerformed(java.awt.event.ActionEvent evt) {

		tfMain.setText(tmp + "9");
		tmp = tmp + "9";

	}

	private void plusActionPerformed(java.awt.event.ActionEvent evt) {
		
		switch (saveHere) {
		case "+":
			if (tmp != "") {
				firstInt = firstInt + Integer.parseInt(tmp);
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "+";
				tfMain.setText(saveHere);
				break;
			}
		case "-":
			if (tmp != "") {
				firstInt = firstInt - Integer.parseInt(tmp);
				saveHere = "+";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			}else {
			saveHere = "+";
			tfMain.setText(saveHere);
			break;
			}
		case "*":
			if (tmp != "") {
				firstInt = firstInt * Integer.parseInt(tmp);
				saveHere = "+";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			}else {
			saveHere = "+";
			tfMain.setText(saveHere);
			break;
			}
		case "/":
			if (tmp != "") {
				firstInt = firstInt / Integer.parseInt(tmp);
				saveHere = "+";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			}else {
			saveHere = "+";
			tfMain.setText(saveHere);
			break;
			}

		default:
			if (tmp != "+" && tmp != "-" && tmp != "*" && tmp != "/") {
				firstInt = Integer.parseInt(tmp);
				tmp = "";
				saveHere = "+";
				tfMain.setText("+");
				break;
			} else {
				saveHere = "+";
				tfMain.setText(saveHere);
				break;
			}
		}

	}

	private void minusActionPerformed(java.awt.event.ActionEvent evt) {
		switch (saveHere) {
		case "+":
			if (tmp != "") {
				firstInt = firstInt + Integer.parseInt(tmp);
				saveHere = "-";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "-";
				tfMain.setText(saveHere);
				break;
			}

		case "-":
			if (tmp != "") {
				firstInt = firstInt - Integer.parseInt(tmp);
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "-";
				tfMain.setText(saveHere);
				break;
			}
		case "*":
			if (tmp != "") {
				firstInt = firstInt * Integer.parseInt(tmp);
				saveHere = "-";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "-";
				tfMain.setText(saveHere);
				break;
			}

		case "/":
			if (tmp != "") {
				firstInt = firstInt / Integer.parseInt(tmp);
				saveHere = "-";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "-";
				tfMain.setText(saveHere);
				break;
			}

		default:
			if (tmp != "+" && tmp != "-" && tmp != "*" && tmp != "/") {
				firstInt = Integer.parseInt(tmp);
				tmp = "";
				saveHere = "-";
				tfMain.setText("-");
				break;
			} else {
				saveHere = "-";
				tfMain.setText(saveHere);
				break;
			}
		}
	}

	private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {
		switch (saveHere) {

		case "+":
			if (tmp != "") {
				firstInt = firstInt + Integer.parseInt(tmp);
				saveHere = "*";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "*";
				tfMain.setText(saveHere);
				break;
			}

		case "-":
			if (tmp != "") {
				firstInt = firstInt - Integer.parseInt(tmp);
				saveHere = "*";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "*";
				tfMain.setText(saveHere);
				break;
			}

		case "*":
			if (tmp != "") {
				firstInt = firstInt * Integer.parseInt(tmp);
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "*";
				tfMain.setText(saveHere);
				break;
			}

		case "/":
			if (tmp != "") {
				firstInt = firstInt / Integer.parseInt(tmp);
				saveHere = "*";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "*";
				tfMain.setText(saveHere);
				break;
			}

		default:
			if (tmp != "+" && tmp != "-" && tmp != "*" && tmp != "/") {
				firstInt = Integer.parseInt(tmp);
				tmp = "";
				saveHere = "*";
				tfMain.setText("*");
				break;
			} else {
				saveHere = "*";
				tfMain.setText(saveHere);
				break;
			}
		}
	}

	private void divisionActionPerformed(java.awt.event.ActionEvent evt) {
		switch (saveHere) {

		case "+":
			if (tmp != "") {
				firstInt = firstInt + Integer.parseInt(tmp);
				saveHere = "/";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "/";
				tfMain.setText("/");
				break;
			}

		case "-":
			if (tmp != "") {
				firstInt = firstInt - Integer.parseInt(tmp);
				saveHere = "/";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "/";
				tfMain.setText("/");
				break;
			}

		case "*":
			if (tmp != "") {
				firstInt = firstInt * Integer.parseInt(tmp);
				saveHere = "/";
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "/";
				tfMain.setText("/");
				break;
			}

		case "/":
			if (tmp != "") {
				firstInt = firstInt / Integer.parseInt(tmp);
				tmp = "";
				tfMain.setText(firstInt + "");
				break;
			} else {
				saveHere = "/";
				tfMain.setText("/");
				break;
			}

		default:
			if (tmp != "+" && tmp != "-" && tmp != "*" && tmp != "/") {
				firstInt = Integer.parseInt(tmp);
				tmp = "";
				saveHere = "/";
				tfMain.setText("/");
				break;
			} else {
				saveHere = "/";
				tfMain.setText(saveHere);
				break;
			}
		}
	}

	private void clearActionPerformed(java.awt.event.ActionEvent evt) {
		tfMain.setText("");
		tmp = "";
		firstInt = firstInt * 0;
		nextInt = nextInt * 0;
		resultInt = resultInt * 0;
	}

	private void resultActionPerformed(java.awt.event.ActionEvent evt) {
		if (tfMain.getText() != "+" && tfMain.getText() != "-" && tfMain.getText() != "*" && tfMain.getText() != "/") {
			nextInt = Integer.parseInt(tmp);
		} else {
			tfMain.setText(firstInt + "");
		}
		switch (saveHere) {
		case "+":
			resultInt = firstInt + nextInt;
			tfMain.setText(resultInt + "");
			firstInt = resultInt;
			tmp = firstInt + "";
			saveHere = "";
			break;
		case "-":
			resultInt = Math.round(firstInt - nextInt);
			tfMain.setText(resultInt + "");
			firstInt = resultInt;
			tmp = firstInt + "";
			saveHere = "";
			break;
		case "*":
			resultInt = firstInt * nextInt;
			tfMain.setText(resultInt + "");
			firstInt = resultInt;
			tmp = firstInt + "";
			saveHere = "";
			break;
		case "/":
			resultInt = firstInt / nextInt;
			tfMain.setText(resultInt + "");
			firstInt = resultInt;
			tmp = firstInt + "";
			saveHere = "";
			break;
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Mycal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton button1;
	private javax.swing.JButton button2;
	private javax.swing.JButton button3;
	private javax.swing.JButton button4;
	private javax.swing.JButton button5;
	private javax.swing.JButton button6;
	private javax.swing.JButton button7;
	private javax.swing.JButton button8;
	private javax.swing.JButton button9;
	private javax.swing.JButton clear;
	private javax.swing.JButton division;
	private javax.swing.JButton minus;
	private javax.swing.JButton multiplication;
	private javax.swing.JButton plus;
	private javax.swing.JButton result;
	private javax.swing.JTextField tfMain;
	// End of variables declaration
}
